xtrans.rb:  handle missing sys/stropts.h
Pull Request: Linuxbrew/homebrew-xorg#454

Closes: Linuxbrew/homebrew-xorg#453

Fedora does not provide `sys/stropts.h`.
As a result, installation of `libx11` fails with:
    Xtranslcl.c:84:26: fatal error: sys/stropts.h: No such file or directory

This PR replaces `sys/stropts.h` with `sys/ioctl.h` in Xtranslcl.c