libxt: make check requires glib
Pull Request: Linuxbrew/homebrew-xorg#461

Fixes the error:
```
error: glib.h: No such file or directory compilation terminated.
```